version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wasteless-postgres
    environment:
      POSTGRES_DB: wasteless_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mariamtinu96
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: wasteless-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wasteless_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Mariamtinu96
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: d822414c7a0f1e16a42c72ae7afa81735223ca300ac66a1da803bf93c2dc9c32e89e1323
      JWT_EXPIRATION: 86400000
      SPOONACULAR_API_KEY: 46e8627295314894b610e4ec2cac7658
      SPOONACULAR_API_BASE_URL: https://api.spoonacular.com
      PORT: 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
